"""my tables

Revision ID: 96671e2b62a6
Revises: 1eb7fb9f3d48
Create Date: 2023-04-27 13:31:36.916642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96671e2b62a6'
down_revision = '1eb7fb9f3d48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
